COMP003B.Assignment2/Models/ErrorViewModel.cs
namespace COMP003B.Assignment2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

COMP003B.Assignment2/Controllers/HomeController.cs
using System.Diagnostics;
using COMP003B.Assignment2.Models;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

COMP003B.Assignment2/Controllers/InfoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment2.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Hobbies()
        {
            return View();
        }
    }
}

COMP003B.Assignment2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

COMP003B.Assignment2/Views/Info/About.cshtml
@{
    ViewData["Title"] = "About the Application";
    ViewData["Author"] = "by Matthew Tan";
}
<h1>@ViewData["Title"]</h1>
<h2>@ViewData["Author"]</h2>

<p>Semper auctor neque vitae tempus quam pellentesque nec. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Ut venenatis tellus in metus vulputate eu scelerisque. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Tincidunt nunc pulvinar sapien et ligula. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Urna porttitor rhoncus dolor purus non enim. Eleifend mi in nulla posuere sollicitudin. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Dolor sed viverra ipsum nunc aliquet. Cursus mattis molestie a iaculis at erat pellentesque. Facilisis mauris sit amet massa vitae tortor. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae.</p>

COMP003B.Assignment2/Views/Info/Hobbies.cshtml
@{
    ViewData["Title"] = "My Hobbies";
}
<h1>@ViewData["Title"]</h1>

<ul>
    <li>1. Traveling</li>
    <li>2. Music</li>
    <li>3. Watching Sports </li>
</ul>

COMP003B.Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COMP003B.Assignment2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMP003B.Assignment2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COMP003B.Assignment2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Hobbies">Hobbies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - COMP003B.Assignment2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>